# Generated by Django 4.2 on 2026-05-23 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_fooddiaryentry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpantry',
            name='quantity_g',
        ),
        migrations.AddField(
            model_name='userpantry',
            name='quantity',
            field=models.FloatField(default=0, help_text='Количество в граммах или штуках'),
        ),
        migrations.AddField(
            model_name='userpantry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userpantry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.product'),
        ),
        migrations.AlterField(
            model_name='userpantry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
